include: package:flutter_lints/flutter.yaml

analyzer:

  errors:
    # 使われていないプロパティのアラートを消す
    unused_local_variable: false
    # const 付け忘れを教えてくれる
    prefer_single_quotes: true
    # カンマ 付け忘れを教えてくれる
    # require_trailing_commas: true

linter:
  rules:
    # シングルクオーテーション に統一
    - prefer_single_quotes
