// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRF_HOtHI0837ibDQ3dXif7pZYSBreM4',
    appId: '1:638123334577:web:fe95090a0bd931d0287b90',
    messagingSenderId: '638123334577',
    projectId: 'pastquiz0123',
    authDomain: 'pastquiz0123.firebaseapp.com',
    storageBucket: 'pastquiz0123.appspot.com',
    measurementId: 'G-V5KPXRWBKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq6MrShJylCJZwCcFdaldl3L086BE527Q',
    appId: '1:638123334577:android:2f8049f69d85025a287b90',
    messagingSenderId: '638123334577',
    projectId: 'pastquiz0123',
    storageBucket: 'pastquiz0123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xHQ3ZDw2v99eITLLNQFzoI8Jit1xPpA',
    appId: '1:638123334577:ios:c0d6bc73bcd074b4287b90',
    messagingSenderId: '638123334577',
    projectId: 'pastquiz0123',
    storageBucket: 'pastquiz0123.appspot.com',
    iosClientId: '638123334577-68g1papk310vd093r57ptjsl5nk11sbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pastQuestions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7xHQ3ZDw2v99eITLLNQFzoI8Jit1xPpA',
    appId: '1:638123334577:ios:c0d6bc73bcd074b4287b90',
    messagingSenderId: '638123334577',
    projectId: 'pastquiz0123',
    storageBucket: 'pastquiz0123.appspot.com',
    iosClientId: '638123334577-68g1papk310vd093r57ptjsl5nk11sbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pastQuestions',
  );
}
